### ISSUE TITLE
iOS local video stream flashes to video off briefly when joining a call with video on [iOS]

### ISSUE THREAD

**Issue by AmyL219** [Azure/Communication#191]
**Describe the bug**
When the app join a call successfully with local video on, the local video stream will have a flash black screen bug showing up. [See my video 0:03-0:05]

**Screenshots**
https://user-images.githubusercontent.com/75647512/108126799-1d41fd00-705f-11eb-8896-50d28ac16dfd.mov

**Smartphone (please complete the following information):**
 - Device: iphoneSE
 - OS: iOS 14
 - Version: 'AzureCommunicationCalling', '1.0.0-beta.8'

**Logs**
[xcappdata.zip](https://github.com/Azure/Communication/files/5991866/xcappdata.zip)

**Comment by sankum-msft** [comment]
@AmyL219 this was fixed a day after you reported this. Can you please confirm that it is fixed for you now?

**Comment by AmyL219** [comment]
@sankum-msft, I tested it with  '1.0.0-beta.8', and the local video stream flashes is still there.

**Comment by AmyL219** [comment]
[ADO ticket](https://skype.visualstudio.com/SPOOL/_workitems/edit/2399779)

**Comment by jimchou-dev** [comment]
Issue still persist after upgrading calling SDK to v1.0.1

https://user-images.githubusercontent.com/77021369/117220380-f7a1d580-adbb-11eb-9ba3-b64b4b0deadb.mov
