### ISSUE TITLE
[iOS] Unable to build/run Azure Communication Calling 2.0.0-beta.1

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#344]
**Describe the bug**
Unable to build/run Azure Communication Calling 2.0.0-beta.1

**To Reproduce**
1. Install AzureCommunicationCalling via cocoapods
2. Build/run app
3. Observe library loading error: `dyld: Library not loaded: @rpath/AzureCore.framework/AzureCore`

**Expected behavior**
Should be able to run application with AzureCommunicationCalling dependency without issue.

**Screenshots**
```
dyld: Library not loaded: @rpath/AzureCore.framework/AzureCore
  Referenced from: /Users/respirit/Library/Developer/CoreSimulator/Devices/5181C875-8991-4756-98D0-3591869B5BC7/data/Containers/Bundle/Application/D388D70B-6CC0-4A72-9B58-177D8A5F1961/LIConferencingSampleApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling
  Reason: image not found
```

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max (Simulator)
 - OS: iOS 14.0
 - Xcode 12.0

**Additional context**
It looks like the AzureCommunicationCalling pod is not properly pulling down its dependency (AzureCore), as I also don't see an AzureCore pod generated for my workspace.

**Comment by raosanat** [comment]
@ryanespiritu can you please manually add AzureCore as dependency for now. The reason is AzureCommunicationCommon dependency on AzureCore was removed in latest version and we a new Swift API extensions in AzureCommunicationCalling which was built with older version of AzureCommunicationCommon which relied on AzureCore. Even though AzureCore is not used its required for linking , we will fix this in the upcoming version.

**Comment by ryanespiritu** [comment]
Hi @raosanat thanks for your response. I've added AzureCore 1.0.0-beta.12 as a dependency but now see a new runtime error below:

```
dyld: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: /Users/respirit/Library/Developer/CoreSimulator/Devices/5181C875-8991-4756-98D0-3591869B5BC7/data/Containers/Bundle/Application/921D30AE-0D6B-42B8-9D7D-ECF8EF753D84/LIConferencingSampleApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling
  Expected in: /Users/respirit/Library/Developer/CoreSimulator/Devices/5181C875-8991-4756-98D0-3591869B5BC7/data/Containers/Bundle/Application/921D30AE-0D6B-42B8-9D7D-ECF8EF753D84/LIConferencingSampleApp.app/Frameworks/AzureCore.framework/AzureCore
 in /Users/respirit/Library/Developer/CoreSimulator/Devices/5181C875-8991-4756-98D0-3591869B5BC7/data/Containers/Bundle/Application/921D30AE-0D6B-42B8-9D7D-ECF8EF753D84/LIConferencingSampleApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/respirit/Library/Developer/CoreSimulator/Caches/dyld/20F71/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/respirit/Library/Developer/Xcode/DerivedData/LIConferencing-bdeukwvawvftjjdoiqunnnvsctog/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer
```

**Comment by raosanat** [comment]
Do you see the same thing on device or is it a simulator issue only ?

**Comment by ryanespiritu** [comment]
@raosanat Same thing on device as well. (iPhone 11 Pro - iOS 14.4.2)

```
dyld: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
```

**Comment by raosanat** [comment]
Which version of AzureCommunicationCommon are you using ? And you are not using CocoaPods right ?

**Comment by raosanat** [comment]
cc: @JoshuaLai

**Comment by mkambale** [comment]
@raosanat, @JoshuaLai in addition to this,  'AzureCore', '~> 1.0.0-beta.11' included, it still throws same error.

**Comment by yasheedv** [comment]
Facing same issue. Did you find any solution?

**Comment by JoshuaLai** [comment]
As a work around can you try forcing `pod 'AzureCommunicationCommon', '1.0.0' `  run a `pod update` after that

**Comment by raosanat** [comment]
There seems to be 2 problems here. 

*1. Problem*

1. AzureCommunicationCommon had a breaking change in 1.0.1 which makes AzureCommunicationCalling not compatible with 2.0.0-beta.1 as AzureCommunicationCalling was was built with 1.0.0. 

*Solution*
In your applications Podfile manually add this line for now
`pod 'AzureCommunicationCommon', '~> 1.0.0'`

As @JoshuaLai suggested above

*2. Problem*

1. If you do the above and still see a runtime error

*Solution*
If you are using XCode 12.0 , please upgrade. We are looking into why 12.0 has this issue and not the latest XCode, this probably is related to the Swift version in XCode 12.0.

**Comment by mkambale** [comment]
@raosanat @JoshuaLai I tried below combination with xcode 12.0.1 - 

   pod 'AzureCommunicationCalling', '~> 2.0.0-beta.1'
   pod 'AzureCommunication', '~> 1.0.0-beta.12'
   pod 'AzureCore', '~> 1.0.0-beta.11'
   pod 'AzureCommunicationCommon', '~> 1.0.0'

I still face same issue. App that we building basically a Teams interop app, help me to identify the correct latest set of pods for this.

**Comment by JoshuaLai** [comment]
@mkambale Sorry I don't understand the combination you are trying with the cross out. Can you just show us a snippet of the pod file. @raosanat did also discover there might be an Xcode 12.0 issue have you tried upgrading to Xcode 12.5.1 ?

**Comment by tjprescott** [comment]
```
pod 'AzureCommunicationCalling', '2.0.0-beta.1'
pod 'AzureCommunicationCommon', '1.0.0'
```

You shouldn't have any references to AzureCore or AzureCommunication (which is an old deprecated version of AzureCommunicationCommon) in your podfile at all.

**Comment by jonathanellis** [comment]
I'm not a user of Azure Communication Calling but I've been tracking down this issue in another framework. Looking around, it seems this is probably related to this issue [here](https://github.com/contentful/contentful-persistence.swift/issues/116), which was fixed [in this PR here](https://github.com/contentful/contentful.swift/pull/341).

Apparently this is being caused by the following warning, which now seems to turn into a fatal dyld issue when linking to binary frameworks... 😬

> Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

Any info anyone has on this issue would be much appreciated!

**Comment by mkambale** [comment]
@JoshuaLai @tjprescott Thank you.
With just these two pods -
pod 'AzureCommunicationCalling', '2.0.0-beta.1'
pod 'AzureCommunicationCommon', '1.0.0'

And on xcode 12.5.1, I am able to build the app.
We can consider closing this issue.

**Comment by aahmed92021** [comment]
@mkambale I have tried the exact same combination as you did. But I amm still facing the runtime crash issue? You sure the app stopped crashing for you?

**Comment by raosanat** [comment]
Please try with the latest release [v2.0.1-beta.1](https://github.com/Azure/Communication/releases/tag/v2.0.1-beta.1).

**Comment by aahmed92021** [comment]
> Please try with the latest release [v2.0.1-beta.1](https://github.com/Azure/Communication/releases/tag/v2.0.1-beta.1).

Didn't work. Xcode: 12.5.1

**Comment by aahmed92021** [comment]
@raosanat even the latest version didn't work :O
