### ISSUE TITLE
Web: Group Call ends once all but 1 participant leaves?

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#68]
**Is your feature request related to a problem? Please describe.**
When a group call is started, it is possible for there to be 1 participant. Other participants can join. The call continues until there is only one participant left. At that point the group call terminates.

Unsure if this is intended behavior or a bug. Our thinking was that a group call continues until the last participant leaves. 

For all participants, we use `hangUp({forEveryone: false})` which should prevent terminating the call for everyone.

What is the expected behavior of group calls in this case?

**Comment by akania** [comment]
Hi @eliaspuurunen , you're correct , current behavior is that group call allows participants to join but it will terminate once participant count goes below 2.
Do you have a specific scenario in mind where you'd like last participant to stay connected?

**Comment by eliaspuurunen** [comment]
Hi @akania - I do have a scenario.

Example: group calls where participants rotate between groups. Each group has 1 moderator. The participants are grouped together but rotate between calls as one. We currently have a workaround where we have _two_ people as moderators so the group call stays active.

**Comment by parkjohnston** [comment]
I have a need for this as well - is this group open to external PRs? 

Would be more than happy to correct this.

**Comment by devwheel** [comment]
I would add a scenario - think of telemedicine with virtual receptionist/doctor + patient.  virtual receptionist (or video helpdesk) works with patient and then drops out waiting for doctor.  It bumps the patient out of the call?

**Comment by mariusu-msft** [comment]
Hi folks,

Quick update here, this should be fixed in the next release.

-Marius

**Comment by eliaspuurunen** [comment]
Epic! Will we need to do anything to our code?

**Comment by akania** [comment]
no, this will be internal change. we'll update this thread once we have it published.

**Comment by mariusu-msft** [comment]
@eliaspuurunen, @devwheel this has now been released with version 1.0.0-beta.2

Can you please verify all works as you are expecting?

I am closing this, please reopen if you encounter any issues.

AB#2290702

**Comment by eliaspuurunen** [comment]
We are still seeing existing behavior - if a group call has 1 member left, it is ended.

**Comment by mariusu-msft** [comment]
Reopening while investigating.

@eliaspuurunen can you confirm you are running latest library on all endpoints

Please share a call Id for investigation please.

**Comment by eliaspuurunen** [comment]
Call ID: "732d8000-c887-42bc-8b47-c879056464c2"

Confirmed latest library on all web endpoints and server too.

**Comment by mariusu-msft** [comment]
@eliaspuurunen this seems to be a different issue than before. We're investigating. 

Meanwhile - you please provide a snippet of how you are establishing the group call? There seems to be something weird about how the call is being set up.

**Comment by mariusu-msft** [comment]
@eliaspuurunen are you still observing this behavior. We have since made more changes in the backend and we believe this to be fixed. 

If you still have a repro, please provide a callId and snippet of how you are establishing the call.

Thanks for your report.

**Comment by cngeru** [comment]
@mariusu-msft What's the maximum number of users that can participate on a call ?

**Comment by mariusu-msft** [comment]
https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features

@cngeru we support maximum of 350 participants.

**Comment by mariusu-msft** [comment]
@eliaspuurunen I am closing this ticket at this time. We are not aware of any new issues regarding groupId based calls ending when all by 1 participants leavings

**Comment by cngeru** [comment]
@mariusu-msft What does this mean [https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-client-library-streaming-support](url) and can all the 350 be talking ?
